name: Jupyter Book — Build & Deploy

on:
  push:
    branches: [main, master]
    paths:
      - "2025_AMPH_JHU/**"
      - "**/*.ipynb"
      - "**/*.md"
      - "_config.yml"
      - "_toc.yml"
      - "requirements*.txt"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "2025_AMPH_JHU/**"
      - "**/*.ipynb"
      - "**/*.md"
      - "_config.yml"
      - "_toc.yml"
      - "requirements*.txt"
      - ".github/workflows/*.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: jupyter-book-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  BOOK_DIR: "2025_AMPH_JHU"   # <--- change to your book directory

jobs:
  build:
    name: Build book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install jupyter-book
          fi

      - name: Build Jupyter Book
        run: |
          jupyter-book build "${BOOK_DIR}" --warningiserror -n --keep-going

      # Upload the book's HTML as an artifact (exactly as the website shows)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ env.BOOK_DIR }}/_build/html"

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Deploy the book's HTML to GitHub Pages (exactly as the website shows)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
